sudo: false
cache: bundler
before_script:
  - psql -c 'create database dummy_test;' -U postgres
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
matrix:
  exclude:
    - rvm: 2.6.3
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5_0.gemfile
