# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4be083c34300c2717abe4f5981d4ccf79d9f62c91b11073d4a1a130db39fb2f8b699ac57fd227828c5ea587868896ae477a19823423cb13329264031d21b6c93

test:
  secret_key_base: faad8e70667156ffde1f188399e61bb01eaeb8864af06637cb31feeaf82426b0e16024fa8bb726d7f219320cac167a1b860f461df6dccac54bc5ab78088665b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
